version: "3.8"
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Kolkata        # Change to your local timezone
    ports:
      - 5055:5055              # Change if you want a different port
    volumes:
      - ./config:/app/config
    restart: unless-stopped

