version: '3.7'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    ports:
      - 8080:80
    volumes:
      - ./heimdall/config:/config
    environment:
      - PUID=1000      # change based on your user
      - PGID=1000      # change based on your group
      - TZ=Asia/Kolkata
    restart: unless-stopped
