version: '3.7'

services:

  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: mysecretroot
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - /mnt/t5/nextcloud_db:/var/lib/mysql

  app:
    image: nextcloud
    restart: always
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - /mnt/wdhdd/nextcloud/data:/var/www/html/data
      - /mnt/wdhdd/nextcloud/config:/var/www/html/config

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    ports:
      - 9981:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=my_super_secret_key

