version: '3.7'

services:

  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: mysecretroot
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - /mnt/t5/nextcloud_db:/var/lib/mysql

  app:
    image: nextcloud:apache
    container_name: nextcloud_app
    restart: always
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: nextcloudpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - /mnt/wdhdd/nextcloud:/var/www/html

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    ports:
      - 9981:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=my_super_secret_key
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
